# Generated by Django 4.1 on 2022-10-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='post',
        ),
    ]
