# Generated by Django 4.1 on 2022-11-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_likedis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedis',
            old_name='votes',
            new_name='vote',
        ),
    ]
